 package Controlador;

import Controlador.iConstantes;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author david
 */
public class Tablero extends javax.swing.JFrame implements iConstantes{

    private final int BTNTAMANO = 20;
    private final int DIMENSION = 30;

    private Tablero tablero;
    private JButton botones[][];

    public Tablero() {
        initComponents();
        tablero = this;
        initTablero();
    }

    private void initTablero() {
        botones = new JButton[DIMENSION][DIMENSION];
        for (int i = 0; i < DIMENSION; i++) {
            for (int j = 0; j < DIMENSION; j++) {
                botones[i][j] = new JButton();
                botones[i][j].setName(i + "_" + j);
                botones[i][j].setBounds(j * BTNTAMANO, i * BTNTAMANO, BTNTAMANO, BTNTAMANO);
                botones[i][j].setBackground(Color.white);
                pnlPantalla.add(botones[i][j]);
            }

        }
    }

    public void Click(java.awt.event.MouseEvent evt) {
        System.out.println(evt.getComponent().getName());
    }
    
    public void setBackGround(int position[], int agente)
    {
        switch(agente)
        {
            case JUGADOR:
                botones[position[X]][position[Y]].setBackground(BG_JUGADOR);
                break;
            case ALIADO:
                botones[position[X]][position[Y]].setBackground(BG_ALIADO);
                break;
            case ENEMIGO:
                botones[position[X]][position[Y]].setBackground(BG_ENEMIGO);
                break;
            case 3:
                botones[position[X]][position[Y]].setBackground(BG_WHITE);
                break;
            default:
                
        }
    }
    public void setAllBackGroundWhite()
    {
        for (int i = 0; i < DIMENSION; i++) {
            for (int j = 0; j < DIMENSION; j++) {
                botones[i][j].setBackground(BG_WHITE);
            }
        }
    }

    public JPanel getPnlPantalla() {
        return pnlPantalla;
    }

    public JPanel getPnlPantalla2() {
        return pnlPantalla2;
    }

    public JButton[][] getBotones()
    {
        return botones;
    }

    public void setTxfEnemigos(String text) {
        this.txfEnemigos.setText(text);
    }

    public void setTxfVida(String vida) {
        this.txfVida.setText(vida);
    }

    public void setTxfFin(String text) {
        this.txfFin.setText(text);
    }

    public void setTxfAliadosSalvados(String text) {
        this.txfAliadosSalvados.setText(text);
    }

    public void setTxfEnemigosEliminados(String text) {
        this.txfEnemigosEliminados.setText(text);
    }

    public void setTxfAliados(String text) {
        this.txfAliados.setText(text);
    }

    public void setLblDownText(String text) {
        this.lblDownText.setText(text);
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPantalla = new javax.swing.JPanel();
        pnlPantalla2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txfVida = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txfEnemigos = new javax.swing.JLabel();
        txfFin = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txfAliados = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txfAliadosSalvados = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txfEnemigosEliminados = new javax.swing.JLabel();
        lblDownText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPantalla.setBackground(new java.awt.Color(204, 255, 204));
        pnlPantalla.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlPantalla.setPreferredSize(new java.awt.Dimension(600, 600));

        javax.swing.GroupLayout pnlPantallaLayout = new javax.swing.GroupLayout(pnlPantalla);
        pnlPantalla.setLayout(pnlPantallaLayout);
        pnlPantallaLayout.setHorizontalGroup(
            pnlPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 596, Short.MAX_VALUE)
        );
        pnlPantallaLayout.setVerticalGroup(
            pnlPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 596, Short.MAX_VALUE)
        );

        pnlPantalla2.setBackground(new java.awt.Color(255, 204, 204));
        pnlPantalla2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Vida:");

        txfVida.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txfVida.setText("0");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Enemigos");

        txfEnemigos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txfEnemigos.setText("0");

        txfFin.setBackground(new java.awt.Color(255, 0, 0));
        txfFin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txfFin.setForeground(new java.awt.Color(255, 51, 51));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Aliados");

        txfAliados.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txfAliados.setText("0");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Aliados Salvados");

        txfAliadosSalvados.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txfAliadosSalvados.setText("0");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Enemigos eliminados");

        txfEnemigosEliminados.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txfEnemigosEliminados.setText("0");

        lblDownText.setBackground(new java.awt.Color(51, 51, 255));
        lblDownText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout pnlPantalla2Layout = new javax.swing.GroupLayout(pnlPantalla2);
        pnlPantalla2.setLayout(pnlPantalla2Layout);
        pnlPantalla2Layout.setHorizontalGroup(
            pnlPantalla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txfFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlPantalla2Layout.createSequentialGroup()
                .addGroup(pnlPantalla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPantalla2Layout.createSequentialGroup()
                        .addGroup(pnlPantalla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlPantalla2Layout.createSequentialGroup()
                                .addGroup(pnlPantalla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlPantalla2Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(61, 61, 61))
                                    .addGroup(pnlPantalla2Layout.createSequentialGroup()
                                        .addGroup(pnlPantalla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(18, 18, 18)))
                                .addGap(47, 47, 47)))
                        .addGroup(pnlPantalla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPantalla2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txfAliadosSalvados))
                            .addGroup(pnlPantalla2Layout.createSequentialGroup()
                                .addGroup(pnlPantalla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txfAliados)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlPantalla2Layout.createSequentialGroup()
                                        .addGap(96, 96, 96)
                                        .addComponent(txfEnemigos))
                                    .addComponent(txfVida))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(pnlPantalla2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txfEnemigosEliminados)))
                .addContainerGap())
            .addComponent(lblDownText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlPantalla2Layout.setVerticalGroup(
            pnlPantalla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPantalla2Layout.createSequentialGroup()
                .addGroup(pnlPantalla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPantalla2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPantalla2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txfVida, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPantalla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfEnemigos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPantalla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfAliados, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPantalla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfAliadosSalvados, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPantalla2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfEnemigosEliminados, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(txfFin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDownText, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlPantalla2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlPantalla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPantalla2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblDownText;
    private javax.swing.JPanel pnlPantalla;
    private javax.swing.JPanel pnlPantalla2;
    private javax.swing.JLabel txfAliados;
    private javax.swing.JLabel txfAliadosSalvados;
    private javax.swing.JLabel txfEnemigos;
    private javax.swing.JLabel txfEnemigosEliminados;
    private javax.swing.JLabel txfFin;
    private javax.swing.JLabel txfVida;
    // End of variables declaration//GEN-END:variables
}
